### ISSUE TITLE
Select as addon

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2-bootstrap-theme#4]
How can I make select2 as addon, select width - 0px?

``` js
<div class="input-group select2-bootstrap-append">
    <input type="text" />
    <span class="input-group-btn">
        <select class="select2"></select>
    </span>                     
</div>
```

**Comment by btaens** [comment]
I was just about to open a similar ticket.

This kind of works:

``` html
<div class="input-group">
  <span class="input-group-btn">
    <div class="form-group select">
        <select name="country_code" class="form-control">
            <option value="1">
                Country 1
            </option>
            <option value="2">
                Country 2
            </option>
        </select>
    </div>
  </span>
  <input name="company_mobile" class="form-control" value="" type="phone">
  <span class="input-group-btn">
    <button type="button" title="Call" class="btn btn-success">
        <i class="glyphicon glyphicon-earphone"></i>
    </button>
  </span>
</div>
```

The only problem is, _.input-group-btn_ defines font-size as 0, which makes select2's result font-size 0, so the selected option doesn't show up.

Now, this is technically a hack of bootstrap, as you're only supposed to put buttons in input-group-btn, but this worked really well with the old version of select2-bootstrap3-css, as that defined font-size in its own css.

Don't know if this is technically a bug, or if defining a font-size would cause problems elsewhere.

**Comment by Knoxvillekm** [comment]
Bad solution, but it work:

``` css
.input-group .input-group-btn .select2-container--bootstrap {
  display: table-cell;
}

.input-group.select2-bootstrap-prepend .input-group-btn .select2-container--bootstrap {
  margin-left: -1px;
  margin-right: 1px;
}

.input-group.select2-bootstrap-append .input-group-btn .select2-container--bootstrap {
  margin-left: 1px;
  margin-right: -1px;
}
```
