### ISSUE TITLE
Boostrap 3.37 correct height

### ISSUE THREAD

**Issue by grisotto** [select2/select2-bootstrap-theme#57]
In the https://github.com/select2/select2-bootstrap-theme/blob/master/dist/select2-bootstrap.css

I needed to change this
```css
.select2-container--bootstrap .select2-selection--single {
  height: 34px;
  line-height: 1.42857143;
  padding: 6px 24px 6px 12px;
  /**
     * Adjust the single Select2's dropdown arrow button appearance.
     */
}
```

To 
```css
.select2-container--bootstrap .select2-selection--single {
  height: 44px;
  line-height: 1.42857143;
  padding: 10px 24px 6px 12px;
  /**
     * Adjust the single Select2's dropdown arrow button appearance.
     */
}
```
![before](https://cloud.githubusercontent.com/assets/848173/21081755/3fb7afc0-bfb4-11e6-891b-e8d4f49698e7.png)

![after](https://cloud.githubusercontent.com/assets/848173/21081754/373d8766-bfb4-11e6-81b5-5ef844ed4d1f.png)

my html code:

```html
<div class="input-group">
           <div class="form-group">
                   <select data-placeholder="Selecione um aluno" class="form-control " id="aluno" >
                               <option>1</option>
                               <option>2</option>
                    </select>
            </div>
            <div class="input-group-btn">
                    <button type="submit" name="save"  value="Salvar"  class="btn btn-success" ><i class="glyphicon glyphicon-plus"></i></button>
             </div>
</div>

```
