### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by bangzek** [select2/select2-bootstrap-theme#60]
Is there bootstrap 4 version?

**Comment by RandyBooth** [comment]
+1

**Comment by RandyBooth** [comment]
@bangzek Here what I found that can use this for now if you use SASS.

http://avladov.com/blog/494/select2-with-bootstrap4

**Comment by achimha** [comment]
Needs three more lines:

```
$s2bs-input-border: #ccc !default;
$s2bs-clear-selection-hover-color: $btn-primary-color !default;
$s2bs-remove-choice-hover-color: $btn-primary-color !default;
```

**Comment by jwtoler** [comment]
Anybody have an issue with multiple select and the selected tags not being vertically centered?

**Comment by Alicia-L** [comment]
@jtoler: I had a problem with the text inside a single-choice select2 not being properly centered and figured out the reason (at least with bootstrap v4.0.0-alpha.6). In bootstrap's `_variables.scss`, the input line height is defined without a unit:

`input-line-height:              1.25 !default;`

When that's the case, this number should be multiplied by the font size to obtain the actual line height. So in the `select2-bootstrap4.scss` file in the link above you need to replace this...

```
$s2bs-input-height-base: calc(#{$input-padding-y * 2 + $input-line-height} + #{$border-width * 2}) !default;
$s2bs-input-height-large: calc(#{$input-padding-y-lg * 2 + $input-line-height} + #{$border-width * 2}) !default;
$s2bs-input-height-small: calc(#{$input-padding-y-sm * 2 + $input-line-height} + #{$border-width * 2}) !default;
```
...with this...
```
$s2bs-input-height-base: calc(#{$input-padding-y * 2 + $input-line-height * $font-size-base} + #{$border-width * 2}) !default;
$s2bs-input-height-large: calc(#{$input-padding-y-lg * 2 + $input-line-height * $font-size-lg} + #{$border-width * 2}) !default;
$s2bs-input-height-small: calc(#{$input-padding-y-sm * 2 + $input-line-height * $font-size-sm} + #{$border-width * 2}) !default;
```

Note that this assumes that the line height is provided without a unit. To make this more robust it would be a good idea to check whether this is the case and otherwise use the original variable definitions.

I hope that helps with your problem!

**Comment by jwtoler** [comment]
@Alicia-L I tried that but I still getting this:
![screenshot 2017-03-22 10 00 24](https://cloud.githubusercontent.com/assets/17133784/24201455/740dd98a-0ee6-11e7-9642-3ed379e791bd.png)

**Comment by Alicia-L** [comment]
@jtoler: It seems your problem isn't related to line height after all. I'm not using multiple choice myself so I cannot research this in depth but I had a quick look and I see that the problem is that the choices (which have class `.select2-selection__choice`) have a negative top margin. I played around a bit and I figured that if I take this:

```css
.select2-selection__choice {
      color: $s2bs-input-color;
      background: $s2bs-btn-default-bg;
      border: 1px solid $s2bs-btn-default-border;
      border-radius: $s2bs-selection-choice-border-radius;
      cursor: default;
      float: left;
      margin: ($s2bs-padding-base-vertical - 1) 0 0 $s2bs-padding-base-horizontal/2;
      padding: 0 $s2bs-padding-base-vertical;
    }
```
and invert the sign of the top margin (notice the `-` before the parenthesis)...
```css
      margin: -($s2bs-padding-base-vertical - 1) 0 0 $s2bs-padding-base-horizontal/2;
```
it is now vertically centered. It could be that it's a complete coincidence that reversing the sign works. I have no idea whether that makes sense because I haven't looked into why the top margin is calculated as `($s2bs-padding-base-vertical - 1)`. I would recommend that you look into that to find out how this should really be calculated.

Good luck!
Alicia

**Comment by angel-vladov** [comment]
@jtoler, @Alicia-L 

I've  [updated the Gist](https://gist.github.com/angel-vladov/404de94c5f9703fa462838f77a673446). Download the files and let me know if it fixes the issues you were experiencing. 

You'll now need to include 2 files for this to work. One with variables overrides and one with styles overrides.
Here is an example with how the imports should look:
```scss
@import "node_modules/bootstrap/scss/bootstrap";
@import "node_modules/font-awesome/scss/font-awesome";
@import "node_modules/select2/src/scss/core";
@import "select2-bootstrap4.vars"; // Here are variables from the GIST
@import "node_modules/select2-bootstrap-theme/src/select2-bootstrap";
@import "select2-bootstrap4.after"; // Override theme styles
```

The issue was caused by the theme setting the height of `.select2-selection__choice` as `$s2bs-input-height-large - 2`. This `-2` values is fine if size is in pixels but in Bs 4 everything is done using rem and em so we need to remove the -2 pixels. We are already taking the borders into account for the height calculations so this change won't break the layout.

**NOTE:** `input-sm` and `input-lg` were replaced with `form-control-sm` and `form-control-lg` in Bootstrap 4. This is something we'll need to handle later on. Perhaps a full override of the sass file will be better suited for the task.

**Comment by jwtoler** [comment]
Thanks to @angel-vladov  and @Alicia-L ! Works now.

**Comment by Alicia-L** [comment]
@jtoler You're welcome! :)

@angel-vladov Thanks, Angel! In my case single-select boxes are a bit too tall after switching to the new gist. This is fixed if I replace this:

```
$s2bs-input-height-base: calc(#{$input-padding-y * 2 + $input-line-height} + #{$border-width * 2}) !default;
$s2bs-input-height-large: calc(#{$input-padding-y-lg * 2 + $input-line-height} + #{$border-width * 2}) !default;
$s2bs-input-height-small: calc(#{$input-padding-y-sm * 2 + $input-line-height} + #{$border-width * 2}) !default;
```
with this:

```
$s2bs-input-height-base: calc(#{$input-padding-y * 2 + $input-line-height * $font-size-base} + #{$border-width * 2}) !default;
$s2bs-input-height-large: calc(#{$input-padding-y-lg * 2 + $input-line-height * $font-size-lg} + #{$border-width * 2}) !default;
$s2bs-input-height-small: calc(#{$input-padding-y-sm * 2 + $input-line-height * $font-size-sm} + #{$border-width * 2}) !default;
```
as I had done before.

Thanks again!
Alicia

**Comment by jwtoler** [comment]
@angel-vladov @Alicia-L Do you know why it appears I can not type in the search field? I'm using this in a modal w/ alpha-6. I have not actually tested it outside the modal though.

Edit: it works outside the modal

**Comment by rileytaylor** [comment]
I also had to add `$screen-sm-min: 576px !default;` before importing select2-bootstrap. This is because bootstrap has replaced the old media queries and related values with new @mixins (in this case, `media-breakpoint-up`.

**Comment by judetucker** [comment]
Thanks for all of your discovery guys. I have consolidated all of this into a single SCSS file that can simply replace the theme in this repo.

https://gist.github.com/judetucker/f12167df07b09b93590556c3b2d40537

**Comment by edwardmp** [comment]
@judetucker thanks but is anyone else running into the issue that the select title is displayed beneath the select box?

<img width="259" alt="schermafbeelding 2017-05-02 om 02 35 09" src="https://cloud.githubusercontent.com/assets/1686739/25599901/0a0003b4-2ee0-11e7-9d6e-e4625fabd46d.png">

**Comment by djibe89** [comment]
Hi guys.
Here is my WIP for Select2 + Bootsrap 4 + Material Design Bootstrap.

/*** 
	Select2 for Bootstrap 4 and Material Design Bootstrap 
	by djibe
***/

/*To enable a icon juxtaposed, done*/
.select2-container--bootstrap {
  display: inline-block;
}

/*Select2 input style, done*/
.select2-container--bootstrap .select2-selection {
	box-shadow: none;
	box-sizing: content-box;
	background-color: transparent;
	border: none;
	border-bottom: 1px solid #ccc !important;
	border-radius: 0;
	height: 2.1rem;
	font-size: 1rem;
	transition: all .3s;
	margin-top: .2rem;
	/*don't set a margin-bottom*/
}

/* Select2 input placeholder */
.select2-container--bootstrap .select2-search__field::-webkit-input-placeholder {
	color: #757575;
}
.select2-container--bootstrap .select2-search__field:-moz-placeholder {
	color: #757575;
}
.select2-container--bootstrap .select2-search__field::-moz-placeholder {
	color: #757575;
	opacity: 1;
}
.select2-container--bootstrap .select2-search__field:-ms-input-placeholder {
	color: #757575;
}

/* Select2 results in dropdown */
.select2-container--bootstrap .select2-results__option {
	padding: 1rem;
	text-transform: capitalize;
	color: #4285F4;
	line-height: 1.4rem;
	font-weight: 400;
	font-size: 1.2rem;
}

/* Option already selected appearance in dropdown, done*/
.select2-container--bootstrap .select2-results__option[aria-selected=true] {
	background-color: #EEEEEE;
	color: white;
	cursor: not-allowed;
}

/* Option appearance on hover in dropdown, done */
.select2-container--bootstrap .select2-results__option--highlighted[aria-selected] {
	background-color: #4285F4;
}

/* Search box aspect on focus, done */
.select2-container--bootstrap.select2-container--focus .select2-selection, .select2-container--bootstrap.select2-container--open .select2-selection {
	border: none;
	border-radius: 0;
	box-shadow: none;
}

/* Erase all cross icon, done */
.select2-container--bootstrap .select2-selection__clear {
	color: #333;
	font-size: 1.5rem;
}

/* Erase all cross icon on hover, done */
.select2-container--bootstrap .select2-selection__clear:hover {
	color: red;
}

/* Dropdown panel of results, done */
.select2-container--bootstrap .select2-dropdown {
	border: 0;
	border-radius: 0px;
	box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
	margin-top: 0;
	/*transition: all ease-in 0.6s;*/
	
	overflow-y: hidden;
	/*animation-duration: .6s;
	animation-name: unroll;
	animation-timing-function: ease-in;*/
}
@keyframes unroll {
  from {height: 0rem;opacity: 0.8;}
  to {height: 30rem; opacity: 1;}
}

/* Select2 dropdown size, done */
.select2-container--bootstrap .select2-results > .select2-results__options {
	max-height: 30rem; /*MAX HEIGHT OF DROPDOWN */
	overflow-y: auto;
}

/* Select2 input sizing, done */
.select2-container--bootstrap .select2-selection--multiple {
	min-height: 2.1rem;
	line-height: 1.5rem;
	padding: .7rem 0;
	height: auto;
}

/* Select2 input sizing, done ??? */
.select2-container--bootstrap .select2-selection--multiple .select2-selection__rendered {
	line-height: 1.5;
	margin: 0;
	padding: 0;
}

/* Select2 tags style, done */
.select2-container--bootstrap .select2-selection--multiple .select2-selection__choice {
	display: inline-block;
	font-size: 1rem;
	color: rgba(0,0,0,.6);
	padding: 0 12px;
	border-radius: 16px;
	background: #ECEFF1;
	margin: .2rem .1rem;
	line-height: 2rem;
	height: 2rem;
	font-weight: 500;
	box-shadow: 0 2px 5px 0 rgba(0,0,0,.16), 0 2px 10px 0 rgba(0,0,0,.12);
	border: 0; /*border just below placeholder*/
}

/* Select2 placeholder then active section of input, done */
.select2-container--bootstrap .select2-selection--multiple .select2-search--inline .select2-search__field {
	padding: 0 12px 0 0;
	height: 2rem;
	line-height: 2rem;
	margin-top: 0;
	width: 100% !important; /*don't reduce or crops placeholder*/
	border: none;
}

/* Select2 erase the tag cross, done */
.select2-container--bootstrap .select2-selection--multiple .select2-selection__choice__remove {
	color: #333;
	margin-right: .4rem;
	font-size: 1.2rem;
}

/* Select2 erase the tag cross on hover, done */
.select2-container--bootstrap .select2-selection--multiple .select2-selection__choice__remove:hover {
	color: red;
}

**Comment by judetucker** [comment]
@edwardmp your select2 is not initialized properly. Might not be getting the CSS. check your config.

**Comment by djibe89** [comment]
Hi guys, here is the code and the example for Bootstrap 4 + Material design bootstrap:
[https://jsfiddle.net/djibe89/gzw4un9r/](url)

**Comment by odahcam** [comment]
@djibe could ya properly format the code? At this time, markdown is cutting some pieces of it because you posted as regular text.

**Comment by judetucker** [comment]
Here is the update for the new bootstrap 4 beta!

https://gist.github.com/judetucker/77fc1da23a70e9b15c21decd0bf74bec

**Comment by DaleMckeown** [comment]
Here is a more thorough implementation for Bootstrap 4 Beta, based on @judetucker's implementation for Bootstrap Alpha 6.

If anyone discovers any issues, please let me know.

https://gist.github.com/DaleMckeown/82995dcc482650f130a708f11a66a2a6

**Comment by paulm17** [comment]
@DaleMckeown 

Sorry for more noise over here.  But how to use your gist?  I commented on it.  Everything seems to load, but doesn't work as per the images you posted.

**Comment by quasipickle** [comment]
@paulm17 I just commented on how I got my setup to work.

**Comment by paulm17** [comment]
@quasipickle @DaleMckeown Thanks very much for filling in the blanks to that gist.

Can I further inconvenience someone else please?  

Can someone provide a (compiled) css file?

I have node-sass installed, but honestly I have never worked or learnt sass and I don't have a build process with node (just yet).

Thanks

**Comment by DaleMckeown** [comment]
Hi,

I can provide CSS, but it would be specific to my build - for example,
non-rounded corrners, colours specific to my theme, etc. You'd then have to
modify it yourself.

SASS really isn't that hard to grasp - It's worth the small amount of time
required to learn it.

**Comment by paulm17** [comment]
@DaleMckeown Would be awesome if you can.  It's just really a band-aid for me to get to the next step of my project.

I do appreciate SASS is easy to learn.  I'll be sure to do that next year when I port over from jquery to vue.js and a build process.

**Comment by DaleMckeown** [comment]
I've added a seperate, compiled  .css file to the gist.

https://gist.github.com/DaleMckeown/82995dcc482650f130a708f11a66a2a6

**Comment by paulm17** [comment]
@DaleMckeown Many thanks for that, much appreciated!

**Comment by husnulhamidiah** [comment]
@DaleMckeown how do use that css?

I try to import it alongside original select2 css. Here's my code so far. I'm using jade template engine.

``` html
link(rel='stylesheet', href='/static/components/select2/dist/css/select2.min.css')
link(rel='stylesheet', href='/static/css/select2-bootrap4.css')

select#select-status.form-control(name='status')
    option(value='1') Active
    option(value='0') Not Active
```

``` javascript
$('#select-status').select2({
      theme: 'bootstrap'
})
```

But it gives me something like this.
![Image of Yaktocat](https://content.screencast.com/users/hamidiah/folders/Jing/media/da5660ef-7923-4d4d-9156-a043c53d47b0/00000001.png)

**Comment by DaleMckeown** [comment]
Sorry, I don't know about Jade.

**Comment by paulm17** [comment]
@DaleMckeown Just to clarify.  This works perfectly for me.

![Image](https://i.imgur.com/dOMhfzR.png)

Many thanks for that, much appreciated!

**Comment by PascalPixel** [comment]
<img width="354" alt="screen shot 2017-10-20 at 16 26 48" src="https://user-images.githubusercontent.com/3094044/31809632-8e6dd478-b5b3-11e7-9569-76a547008e08.png">

I ended up using the standard select2 theme, and then reverse applying some bootstrap variables 

```scss
.select2-selection--multiple {
  @extend .form-control, .p-1;
}
.select2-container--default .select2-selection--multiple .select2-selection__choice {
  color: white;
  background-color: theme-color("secondary");
  border-color: darken(theme-color("secondary"), 5%);
}
.select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
  color: theme-color("light");
}
.select2-container--default .select2-results__option[aria-selected=true] {
  background-color: lighten(theme-color("secondary"), 25%);
}
.select2-container--default .select2-results__option--highlighted[aria-selected] {
  background-color: theme-color("primary");
}
```

This is sass, if you don't know how to use it, please learn...

-----------------------

### Update

My final code that supports both multiple and single selects is a little more complex sadly
```scss
.select2-container--default,
.select2-container--default.select2-container--focus {
  @extend .w-100;
  .select2-selection {
    @extend .custom-select;
    @extend .pl-1;
    width: 100%;
    height: auto;
    min-height: calc(2.25rem + 2px);

    .select2-selection__choice {
      color: $gray-600;
      background-color: $gray-200;
      border-color: $gray-300;
    }
    .select2-selection__choice__remove {
      color: $gray-400;
      height: 1rem;
    }
  }
  .select2-results__option[aria-selected=true] {
    background-color: lighten(theme-color("secondary"), 25%);
  }
  .select2-results__option--highlighted[aria-selected] {
    background-color: theme-color("primary");
  }
  .select2-selection__arrow {
    display: none;
  }
  .select2-selection--multiple {
    padding: 0 1rem 0 0;
  }
}
```

Result:
<img width="235" alt="screen shot 2017-10-23 at 15 13 37" src="https://user-images.githubusercontent.com/3094044/31874557-ed67bec8-b804-11e7-9730-76ac310ae9ea.png">
